export const GET_CURRENT_SCRIPT = "GET_CURRENT_SCRIPT";
export const GET_CURRENT_VERSE = "GET_CURRENT_VERSE";
export const GET_CURRENT_CHAPTER = "GET_CURRENT_CHAPTER";
export const GET_CURRENT_BOOK = "GET_CURRENT_BOOK";
